language: go

go:
  - 1.11x
  - 1.12x
  - 1.13x

go_import_path: github.com/kodeart/warframe-acolytes

before_deploy:
  - ./build.sh

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: releases/*
  skip_cleanup: true
  on:
    tags: true

script:
  - go test -v -bench=. ./...

notifications:
  email: false
